TheBest/Models/Cuisine.cs
using System.Collections.Generic;

namespace TheBest.Models
{
  public class Cuisine 
  {
    public Cuisine()
    {
      this.Restaurants = new HashSet<Restaurant>();
    }
    public int CuisineId { get; set; }
    public string Style { get; set; }
    public virtual ICollection<Restaurant> Restaurants { get; set; }
  }
}

TheBest/Models/Restaurant.cs
using System.Collections.Generic;

namespace TheBest.Models
{
  public class Restaurant
  {
    public int RestaurantId { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public int Rating { get; set; }
    public int CuisineId { get; set; }
    public virtual Cuisine Cuisine { get; set; }
  }
}

TheBest/Models/TheBestContext.cs
using Microsoft.EntityFrameworkCore;

namespace TheBest.Models
{
  public class TheBestContext : DbContext
  {
    public virtual DbSet<Cuisine> Cuisines { get; set; }
    public DbSet<Restaurant> Restaurants { get; set; }

    public TheBestContext(DbContextOptions options) : base(options) { }
  }
}

TheBest/Controllers/CuisinesController.cs
using Microsoft.AspNetCore.Mvc;
using TheBest.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;

namespace TheBest.Controllers
{
  public class CuisinesController : Controller 
  {
    private readonly TheBestContext _db;

    public CuisinesController(TheBestContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
      List<Cuisine> model = _db.Cuisines.ToList();
      return View(model);
    }
    public ActionResult Create()
    {
      return View();
    }
    [HttpPost]
    public ActionResult Create(Cuisine cuisine)
    {
      _db.Cuisines.Add(cuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Delete(int id)
    {
      var thisCuisine = _db.Cuisines.FirstOrDefault(cuisines => cuisines.CuisineId == id);
      return View(thisCuisine);
    }
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisCuisine = _db.Cuisines.FirstOrDefault(cuisines => cuisines.CuisineId == id); 
      _db.Cuisines.Remove(thisCuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Edit(int id)
    {
      var thisCuisine = _db.Cuisines.FirstOrDefault(cuisines => cuisines.CuisineId == id);
      return View(thisCuisine);
    }
    [HttpPost]
    public ActionResult Edit(Cuisine cuisine)
    {
      _db.Entry(cuisine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
    {
      Cuisine thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      thisCuisine.Restaurants = _db.Restaurants.Where(restaurant => restaurant.CuisineId == id).ToList();
      return View(thisCuisine);
    }
  }
}

TheBest/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace TheBest.Controllers
{
  public class HomeController : Controller
  {
    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
}

TheBest/Controllers/RestaurantController.cs
using Microsoft.AspNetCore.Mvc;
using TheBest.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace TheBest.Controllers
{
  public class RestaurantsController : Controller
  {
    private readonly TheBestContext _db;

    public RestaurantsController(TheBestContext db)
    {
      _db = db; 
    }
    public ActionResult Index()
    {
      List<Restaurant> model = _db.Restaurants.ToList();
      return View(model);
    }
    public ActionResult Create()
    {
      return View();
    }
    [HttpPost]
    public ActionResult Create (Restaurant restaurant)
    {
      _db.Restaurants.Add(restaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantId == id);
      return View(thisRestaurant);
    }
  }
}

TheBest/Controllers/RestaurantsController.cs
using Microsoft.AspNetCore.Mvc;
using TheBest.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;

namespace TheBest.Controllers
{
  public class RestaurantsController : Controller
  {
    private readonly TheBestContext _db;

    public RestaurantsController(TheBestContext db)
    {
      _db = db; 
    }
    public ActionResult Index()
    {
      List<Restaurant> model = _db.Restaurants.ToList();
      return View(model);
    }
    public ActionResult Create()
    {
      ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Style");
      return View();
    }
    [HttpPost]
    public ActionResult Create (Restaurant restaurant)
    {
      _db.Restaurants.Add(restaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantId == id);
      return View(thisRestaurant);
    }
    public ActionResult Edit(int id)
    {
      var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantId == id);
      return View(thisRestaurant);
    }
    [HttpPost]
    public ActionResult Edit(Restaurant restaurant)
    {
      _db.Entry(restaurant).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Delete(int id)
    {
      var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantId == id);
      return View(thisRestaurant);
    }
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantId == id);
      _db.Restaurants.Remove(thisRestaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

TheBest/Views/Cuisines/Create.cshtml
@{
  Layout = "_Layout";
}

@model TheBest.Models.Cuisine

<h4>Add a new cuisine</h4>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Style)
  @Html.TextBoxFor(model => model.Style)

  <input type ="submit" value="Add new cuisine" class="btn btn-default"/>
}

<p>@Html.ActionLink("Show all cuisines", "Index")</p>

TheBest/Views/Cuisines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model TheBest.Models.Cuisine

<h2>Are you sure you want to delete this cuisine?</h2>

@Html.DisplayNameFor(model => model.Style): @Html.DisplayFor(model => model.Style)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to cuisines", "Index")

TheBest/Views/Cuisines/Details.cshtml
@{
  Layout = "_Layout";
}

@using TheBest.Models;
@model TheBest.Models.Cuisine;

<h2>Cuisine Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Style): @Html.DisplayFor(model => model.Style)</h3>

<ul>
@if (@Model.Restaurants.Count == 0)
{
  <p>No restaurants found</p>
}

@foreach (Restaurant restaurant in @Model.Restaurants)
{
  <!-- <li>Description: @restaurant.Description</li> -->
  <li>@Html.ActionLink($"{restaurant.Name}", "Details", "Restaurant", new { id = restaurant.RestaurantId })</li>

}
</ul>

<p>@Html.ActionLink("Back to cuisines", "Index")</p>
<p>@Html.ActionLink("Edit Cuisine", "Edit", new { id = Model.CuisineId })</p>
<p>@Html.ActionLink("Delete Cuisine", "Delete", new { id = Model.CuisineId })</p>

TheBest/Views/Cuisines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model TheBest.Models.Cuisine

<h2>Edit</h2>

<h4>Edit this category: @Html.DisplayFor(model => model.Style)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.CuisineId)

  @Html.LabelFor(model => model.Style)
  @Html.EditorFor(model => model.Style)

  <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to cuisines", "Index")</p>

TheBest/Views/Cuisines/Index.cshtml
@{
  Layout = "_Layout";
}

@using TheBest.Models;
@model List<TheBest.Models.Cuisine>;

<h1>Cuisine Types</h1>

@if(@Model.Count == 0)
{
  <h3>No cuisines have been added yet! Sorry :/</h3>
}

@foreach (Cuisine cuisine in Model)
{
  <li>@Html.ActionLink($"{cuisine.Style}", "Details", new { id = cuisine.CuisineId })</li>
}


<p>@Html.ActionLink("Add new cuisine", "Create", "Cuisines")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

TheBest/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<p>@Html.ActionLink("See all cuisines", "Index", "Cuisines")</p>
<p>@Html.ActionLink("See all restaurants", "Index", "Restaurants")</p>

TheBest/Views/Restaurants/Create.cshtml
@{
  Layout = "_Layout";
}

@model TheBest.Models.Restaurant

<h4>Add New Restaurant</h4>

@using (Html.BeginForm())
{
	@Html.LabelFor(model => model.Name)
	@Html.TextBoxFor(model => model.Name)
	@Html.LabelFor(model => model.Description)
	@Html.TextBoxFor(model => model.Description)
	@Html.LabelFor(model => model.Rating)
	@Html.TextBoxFor(model => model.Rating)

	@Html.LabelFor(model => model.Cuisine)
	@Html.DropDownList("CuisineId")
	<input type="submit" value="Add new restaurant" class="btn-btn-default" />

}
<p>@Html.ActionLink("Show all restaurants", "Index")</p>

<!-- Dana added this  -->

TheBest/Views/Restaurants/Delete.cshtml
@{
  Layout = "_Layout";
}

@model TheBest.Models.Restaurant

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
	<input type="submit" value="Delete"/>
}
@Html.ActionLink("Back to List", "Index")

TheBest/Views/Restaurants/Details.cshtml
@{
	Layout = "_Layout";
}

@model TheBest.Models.Restaurant

<h2>Restaurant Details</h2>

<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
<h3>@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)</h3>
<h3>@Html.DisplayNameFor(model => model.Rating): @Html.DisplayFor(model => model.Rating)</h3>

<p>@Html.ActionLink("Edit Restaurant Details", "Edit", new { id = Model.RestaurantId})</p>
<p>@Html.ActionLink("Delete Restaurant", "Delete", new { id = Model.RestaurantId})</p>

TheBest/Views/Restaurants/Edit.cshtml
  
@{
  Layout = "_Layout";
}

@model TheBest.Models.Restaurant

<h2>Edit</h2>

<h4>Edit this Restaurant: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.RestaurantId)

    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name)
    @Html.LabelFor(model => model.Description)
    @Html.EditorFor(model => model.Description)
    @Html.LabelFor(model => model.Rating)
    @Html.EditorFor(model => model.Rating)

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

TheBest/Views/Restaurants/Index.cshtml
@{
  Layout = "_Layout";
}

@using TheBest.Models;
@model List<TheBest.Models.Restaurant>;

<h1>Restaurants</h1>

@if (@Model.Count == 0)
{
  <h3>No restaurants have been added yet!</h3>
}

@foreach (Restaurant restaurant in Model)
{
	<li>@Html.ActionLink($"{restaurant.Name}", "Details", new {id = restaurant.RestaurantId})</li>
}

<p>@Html.ActionLink("Add new restaurant", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

TheBest/Views/Shared/Footer.cshtml
<div id="footer">©copyright 2020 San Francisco clam chowder suuucks </div>

TheBest/Views/Shared/Header.cshtml
<div id="header"><p>Mariam's Best Restaurants</p></div>

TheBest/Views/Shared/_Layout.cshtml
  
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Mariam's Best</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    <link rel="stylesheet" href='~/css/styles.css'>
    <link href="https://fonts.googleapis.com/css?family=Amiri&display=swap" rel="stylesheet">
  </head>
  <body>
    <div class="container">
      @Html.Partial("Header")
      @RenderBody()
      <br><img src='~/img/hotdog.png'/>
      @Html.Partial("Footer")
    </div>
  </body>